/*
======================================================
DDL Script: create bronze Table
======================================================
Script Purpose : 
this script create a table in the bronze schema, dropping existing tables
if they already exist.
Run this script to re-define theDDL structure of the 'bronze' tables
------------------------------------------------------------------------
*/

IF OBJECT_ID('bronze.crm_cust_info', 'u') IS NOT NULL
DROP TABLEbronze.crm_cust_info;
GO

CREATE TABLE bronze.crm_cust_info(
cst_id int,
cst_key NVARCHAR (50),
cst_firstname NVARCHAR(50),
cst_lastname NVARCHAR(50),
cst_marital_status NVARCHAR(50),
cst_gndr NVARCHAR(50),
cst_create_date date
);
GO

IF OBJECT_ID('bronze.crm_prd_info', 'u') IS NOT NULL
DROP TABLEbronze.crm_prd_info;
GO

create table bronze.crm_prd_info (
prd_id int,
prd_key NVARCHAR(50),
prd_nm NVARCHAR(50),
prd_cost int,
prd_line NVARCHAR(50),
prd_start_dt datetime,
prd_end_dt datetime
);
GO

IF OBJECT_ID('bronze.crm_sales_details', 'u') IS NOT NULL
DROP TABLE bronze.crm_sales_details;
GO

CREATE TABLE bronze.crm_sales_details(
sls_ord_num NVARCHAR(50),
sls_prd_key NVARCHAR(50),
sls_cust_id int,
sls_order_dt int,
sls_ship_dt int,
sls_sales int,
sls_quantity int,
sls_price int
);
  
GO
Create table bronze.erp_loc_a101(
cid NVARCHAR(50),
cntry NVARCHAR(50),
);
GO

IF OBJECT_ID('bronze.erp_cust_az12', 'u') IS NOT NULL
DROP TABLE bronze.erp_cust_az12;
GO

CREATE TABLE bronze.erp_cust_az12(
cid NVARCHAR(50),
bdate DATE,
gen NVARCHAR(50)
);
GO

IF OBJECT_ID('bronze.erp_px_cat_g1v2', 'u') IS NOT NULL
DROP TABLE bronze.erp_px_cat_g1v2;
GO

CREATE TABLE bronze.erp_px_cat_g1v2(
id NVARCHAR(50),
cat NVARCHAR(50),
subcat NVARCHAR(50),
maintanance NVARCHAR(50)
);
GO

